name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ main, irychkov-actions ]
  pull_request:
    branches: [ main, irychkov-actions ]

jobs:
  backend:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22.19.0 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --ci --runInBand

      # -------------------------------
      # 📝 Comment in PR on failure
      # -------------------------------
      - name: Comment on PR if failed
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request?.number;
            if (!pr) {
              core.info('No PR number found; skipping comment.');
              return;
            }
            const body = [
              '**Backend CI** failed.',
              `Commit: \`${process.env.GITHUB_SHA.slice(0,7)}\``,
              `Logs: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body
            });