name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    permissions:
      contents: read
      pull-requests: write
    name: Run frontend tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/cafe-front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.19.0 LTS
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --ci --runInBand

      - name: Run dev server
        run: |
          nohup npm run dev > frontend.log 2>&1 &
          sleep 10
          curl -f http://localhost:5173 || (cat frontend.log && exit 1)

      - name: Comment on PR if failed
        if: ${{ failure() && github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request?.number;
            if (!pr) {
              core.info('No PR number found; skipping comment.');
              return;
            }
            const body = [
              '**Frontend CI** failed.',
              `Commit: \`${process.env.GITHUB_SHA.slice(0,7)}\``,
              `Logs: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
            ].join('\n');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body
            });
